### ISSUE TITLE
handle \u200d delimited emoji

### ISSUE THREAD

**Issue by lsmith77** [ines/spacymoji#20]
Currently `👨🏽‍👩🏽‍👧🏽` is handled as multiple tokens. Note this likely relate to https://github.com/carpedm20/emoji/issues/204

Ideally it would be handled as a single token.

**Comment by bdura** [comment]
Hello @lsmith77, the issue comes from the [tokenizer defaults](https://github.com/explosion/spaCy/blob/master/spacy/lang/char_classes.py#L288). It so happens that 👨 is one of the icons that are looked for during tokenization.

Given the root of the issue, I don't think we'll be able to much about it in the near future... However, you could [customize your tokenizer](https://spacy.io/usage/linguistic-features#native-tokenizers) to avoid splitting the emoji.

**Comment by lsmith77** [comment]
ah bummer .. thx for the feedback though.

**Comment by adrianeboyd** [comment]
I'll close this for now because it looks like it isn't a bug in spacymoji itself.
